version: '3'
services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: 'postgres'
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/study-app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes: 
  bundle:
  db_data:
